### ISSUE TITLE
不太会用诶！请大佬帮忙看看geckodriver.log里说的是啥~我是windows

### ISSUE THREAD

**Issue by Xiao-Zhu-of-PPT** [tomatoF/jksb_sysu#5]
1632461064010	geckodriver	INFO	Listening on 127.0.0.1:5455
1632461067070	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "--marionette" "--headless" "--disable-gpu" "-no-remote" "-profile" "C:\\Users\\yxl20\\AppData\\Local\\Temp\\rust_mozprofileSb3dAg"
*** You are running in headless mode.
1632461067875	Marionette	INFO	Marionette enabled
[GFX1-]: RenderCompositorSWGL failed mapping default framebuffer, no dt
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new NotFoundError("Could not open the file at C:\\Users\\yxl20\\AppData\\Local\\Temp\\rust_mozprofileSb3dAg\\search.json.mozlz4", (void 0)))
1632461069094	Marionette	INFO	Listening on port 5463
1632461069155	RemoteAgent	WARN	TLS certificate errors will be ignored for this session
1632461567130	Marionette	INFO	Stopped listening on port 5463
JavaScript error: resource:///modules/Interactions.jsm, line 230: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIUserIdleService.removeIdleObserver]

###!!! [Parent][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost

1632462453556	geckodriver	INFO	Listening on 127.0.0.1:3834
1632462456620	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "--marionette" "--headless" "--disable-gpu" "-no-remote" "-profile" "C:\\Users\\yxl20\\AppData\\Local\\Temp\\rust_mozprofiledJc57S"
*** You are running in headless mode.
1632462457363	Marionette	INFO	Marionette enabled
[GFX1-]: RenderCompositorSWGL failed mapping default framebuffer, no dt
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new NotFoundError("Could not open the file at C:\\Users\\yxl20\\AppData\\Local\\Temp\\rust_mozprofiledJc57S\\search.json.mozlz4", (void 0)))
1632462458419	Marionette	INFO	Listening on port 8269
1632462458686	RemoteAgent	WARN	TLS certificate errors will be ignored for this session
1632462941684	Marionette	INFO	Stopped listening on port 8269
JavaScript error: resource:///modules/Interactions.jsm, line 230: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIUserIdleService.removeIdleObserver]

**Comment by tomatoF** [comment]
可以注释掉这一行，看看脚本是怎么运行的
options.add_argument("--headless") #设置火狐为headless无界面模式

**Comment by Xiao-Zhu-of-PPT** [comment]
师兄，按你说的注释掉那行代码之后还是不行，我看到打开的火狐浏览器登录界面中，验证码那一行好像一直没有动静。附件里是这次的日志。


另外，请问你在东校吗？如果方便的话能不能当面请教呢~请你吃顿晚饭啥的


在2021年9月24日 ***@***.***> 写道：

可以注释掉这一行，看看脚本是怎么运行的
options.add_argument("--headless") #设置火狐为headless无界面模式

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
1632461064010	geckodriver	INFO	Listening on 127.0.0.1:5455
1632461067070	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "--marionette" "--headless" "--disable-gpu" "-no-remote" "-profile" "C:\\Users\\yxl20\\AppData\\Local\\Temp\\rust_mozprofileSb3dAg"
*** You are running in headless mode.
1632461067875	Marionette	INFO	Marionette enabled
[GFX1-]: RenderCompositorSWGL failed mapping default framebuffer, no dt
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new NotFoundError("Could not open the file at C:\\Users\\yxl20\\AppData\\Local\\Temp\\rust_mozprofileSb3dAg\\search.json.mozlz4", (void 0)))
1632461069094	Marionette	INFO	Listening on port 5463
1632461069155	RemoteAgent	WARN	TLS certificate errors will be ignored for this session
1632461567130	Marionette	INFO	Stopped listening on port 5463
JavaScript error: resource:///modules/Interactions.jsm, line 230: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIUserIdleService.removeIdleObserver]

###!!! [Parent][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost

1632462453556	geckodriver	INFO	Listening on 127.0.0.1:3834
1632462456620	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "--marionette" "--headless" "--disable-gpu" "-no-remote" "-profile" "C:\\Users\\yxl20\\AppData\\Local\\Temp\\rust_mozprofiledJc57S"
*** You are running in headless mode.
1632462457363	Marionette	INFO	Marionette enabled
[GFX1-]: RenderCompositorSWGL failed mapping default framebuffer, no dt
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new NotFoundError("Could not open the file at C:\\Users\\yxl20\\AppData\\Local\\Temp\\rust_mozprofiledJc57S\\search.json.mozlz4", (void 0)))
1632462458419	Marionette	INFO	Listening on port 8269
1632462458686	RemoteAgent	WARN	TLS certificate errors will be ignored for this session
1632462941684	Marionette	INFO	Stopped listening on port 8269
JavaScript error: resource:///modules/Interactions.jsm, line 230: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIUserIdleService.removeIdleObserver]
1632472347188	geckodriver	INFO	Listening on 127.0.0.1:5245
1632472350262	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "--marionette" "--disable-gpu" "-no-remote" "-profile" "C:\\Users\\yxl20\\AppData\\Local\\Temp\\rust_mozprofilePs0fNH"
1632472351166	Marionette	INFO	Marionette enabled
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new NotFoundError("Could not open the file at C:\\Users\\yxl20\\AppData\\Local\\Temp\\rust_mozprofilePs0fNH\\search.json.mozlz4", (void 0)))
1632472353627	Marionette	INFO	Listening on port 5255
1632472353967	RemoteAgent	WARN	TLS certificate errors will be ignored for this session
1632472838467	Marionette	INFO	Stopped listening on port 5255
JavaScript error: resource:///modules/Interactions.jsm, line 230: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIUserIdleService.removeIdleObserver]

###!!! [Parent][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost

**Comment by tomatoF** [comment]
qq942525757

**Comment by tomatoF** [comment]
已解决
