### ISSUE TITLE
推荐一个在线识别验证码的网站

### ISSUE THREAD

**Issue by Editi0** [tomatoF/jksb_sysu#7]
每日100免费额度，自行注册即可，个人测试准确率不错
http://fast.95man.com/

**Comment by Editi0** [comment]
哦对还可以白嫖 GitHub Actions，把 netid 和密码保存到 Secrets，定时运行即可

**Comment by tangkg** [comment]
> 哦对还可以白嫖 GitHub Actions，把 netid 和密码保存到 Secrets，定时运行即可

还能这样操作的吗？我只是用Github Actions搞了个网站，定时运行这个复杂不啊

**Comment by Editi0** [comment]
很简单，可以看我fork的项目

**Comment by tangkg** [comment]
> 很简单，可以看我fork的项目

牛啊大哥，本来想用另一个老哥的docker方法，没用过docker，感觉还挺麻烦的；待会儿回来试试你这个

**Comment by Editi0** [comment]
代码还有点问题，现在还不能用

**Comment by tangkg** [comment]
> 代码还有点问题，现在还不能用

Settings-Secrets中的`OCR_TOKEN`、`NetID`等变量是自行创建吗

**Comment by Editi0** [comment]
对，具体看这里 https://docs.github.com/en/actions/security-guides/encrypted-secrets
